### ISSUE TITLE
link in document cannot be access.

### ISSUE THREAD

**Issue by tinywinds** [parallaxinc/Cloud-Compiler#10]
The Link to Simple IDE with Propeller GCC Installation Instructions is not available in the readme file.

**Comment by zfi** [comment]
The link references a shared Google Doc that is no longer accessible. Can I get a copy of this doc so I can post it in a static public space?

**Comment by tinywinds** [comment]
https://sites.google.com/site/propellergcc/downloads
this link is ok.

**Comment by zfi** [comment]
Closing this issue.
