### ISSUE TITLE
Embedding extended characters in source file comments generate a 500 server error

### ISSUE THREAD

**Issue by zfi** [parallaxinc/Cloud-Compiler#32]
Reported in parallaxinc/solo#283.

Add comment block with this text: ActivityBot 360°
Compiler error : "Compile... A compiler server error '500' has been detected"

**Comment by zfi** [comment]
This error occurs in "./PropCCompiler.py", line 96, in compile/source_file.write(file_content)

The issue is that the default setting for reading and writing files is ASCII, which does not support extended characters. Update file open() calls to specify UTF-8 character set (encoding='utf-8').

**Comment by pjewald** [comment]
This is corrected in the 1.3.8 version of the compiler. Ready for release.

**Comment by zfi** [comment]
Release to staging.
Closing the issue.
