### ISSUE TITLE
WSGI configuration file

### ISSUE THREAD

**Issue by zfi** [parallaxinc/Cloud-Compiler#8]
There is a cloudcompiler.wsgi file in the root of the Demo branch. Is this file actually used in the Demo system or anywhere else? I can't locate it on the Demo server in AWS.

**Comment by PropGit** [comment]
@michel-cf - I can't answer this.  We need your expertise here.

**Comment by michel-cf** [comment]
I don't use it on my local machine, and I guess it's the same on the demo/production system. In all our setups we call uwsgi with the configuration parameters in the command line (from supervisor)

I you wish, or want a more elaborate, shareable config (without having to distribute the command line call), we could work with the cloudcompiler.wsgi file.

So, the file is not actually in use today, but if the content is correct (which looks to be the case), it would be possible to use it.

Some of the things in this wsgi file:
- http host and port
- amount of worker processes to be used
- amount of threads the worker processes use
- max upload size (possibly important for bigger programs)

**Comment by zfi** [comment]
The current production deployment uses separate configuration files for supervisor and cloud-compiler.
